{{ config(
    schema=var('PS_DB_IS_ORA_SCM_v0001.$ORA_SCM_SAC') ,
    materialized='incremental',
    pre_hook='CALL {{ var("PS_DB_IS_ORA_SCM_v0001.$ORA_SCM_SAC") }}.proc_truncate_table(\'{{ var("PS_DB_IS_ORA_SCM_v0001.$ORA_SCM_SAC") }}\',\'{{this}}\');'
) }}


((select BALOP_9.IP_TCV_FULL_CUD_V_ID as IP_TCV_FULL_CUD_V_ID, BALOP_9.IP_ID as IP_ID, BALOP_9.IP_SUP_KEY as IP_SUP_KEY, BALOP_9.MSTR_SRC_STM_CD as MSTR_SRC_STM_CD, BALOP_9.ENT_TP_CD as ENT_TP_CD, BALOP_9.MSTR_SRC_STM_KEY as MSTR_SRC_STM_KEY, BALOP_9.SRC_STM_CD as SRC_STM_CD, BALOP_9.HASH_VAL as HASH_VAL, BALOP_9.VLD_FROM_TMS as VLD_FROM_TMS, BALOP_9.DEL_IN_SRC_STM_IND as DEL_IN_SRC_STM_IND, BALOP_9.SRC_INSTN_ISRT_ID as SRC_INSTN_ISRT_ID, BALOP_9.PCS_ISRT_ID as PCS_ISRT_ID, BALOP_9.ISRT_TMS as ISRT_TMS, BALOP_9.TC_OBJ_INSTANCE_KEY_1 as TC_OBJ_INSTANCE_KEY_1, BALOP_9.TC_OBJ_INSTANCE_KEY_2 as TC_OBJ_INSTANCE_KEY_2, BALOP_9.TC_OBJ_INSTANCE_KEY_3 as TC_OBJ_INSTANCE_KEY_3, BALOP_9.TC_DATA_TYPE_CHAR_IND_CHANGED_NAME as TC_DATA_TYPE_CHAR_IND_CHANGED_NAME, BALOP_9.TC_DATA_TYPE_NCHAR_CD as TC_DATA_TYPE_NCHAR_CD, BALOP_9.TC_DATA_TYPE_VARCHAR_NM as TC_DATA_TYPE_VARCHAR_NM, BALOP_9.TC_DATA_TYPE_NVARCHAR_DSC as TC_DATA_TYPE_NVARCHAR_DSC, BALOP_9.TC_DATA_TYPE_INTEGER_RTO as TC_DATA_TYPE_INTEGER_RTO, BALOP_9.TC_DATA_TYPE_SMALLINT_NBR as TC_DATA_TYPE_SMALLINT_NBR, BALOP_9.TC_DATA_TYPE_BIGINT_PCT as TC_DATA_TYPE_BIGINT_PCT, BALOP_9.TC_DATA_TYPE_DECIMAL_AMT as TC_DATA_TYPE_DECIMAL_AMT, BALOP_9.TC_DATA_TYPE_BOOLEAN_F as TC_DATA_TYPE_BOOLEAN_F, BALOP_9.TC_DATA_TYPE_TIMESTAMP_TMS as TC_DATA_TYPE_TIMESTAMP_TMS, BALOP_9.TC_DATA_TYPE_DATE_DT as TC_DATA_TYPE_DATE_DT, BALOP_9.TC_DATA_TYPE_TIME_TM as TC_DATA_TYPE_TIME_TM, BALOP_9.TC_FK_CL_1_KEY_1 as TC_FK_CL_1_KEY_1, BALOP_9.TC_FK_CL_1_KEY_2 as TC_FK_CL_1_KEY_2, BALOP_9.TC_FK_CL_2_KEY as TC_FK_CL_2_KEY, BALOP_9.TC_FK_EV_I_KEY as TC_FK_EV_I_KEY, BALOP_9.TC_EDC_ATTR_SPLIT as TC_EDC_ATTR_SPLIT, BALOP_9.TC_EDC_ATTR_CONVERGE_1 as TC_EDC_ATTR_CONVERGE_1, BALOP_9.TC_EDC_ATTR_CONVERGE_2 as TC_EDC_ATTR_CONVERGE_2, BALOP_9.TC_FK_1_CL_ID as TC_FK_1_CL_ID, BALOP_9.TC_FK_2_CL_ID as TC_FK_2_CL_ID, BALOP_9.TC_FK_EV_I_ID as TC_FK_EV_I_ID, BALOP_9.TC_SPLIT_ATTR_1_EDC as TC_SPLIT_ATTR_1_EDC, BALOP_9.TC_SPLIT_ATTR_2_EDC as TC_SPLIT_ATTR_2_EDC, BALOP_9.TC_CONVERGE_ATTR_EDC as TC_CONVERGE_ATTR_EDC 
from  
(select  CASE WHEN ( CASE WHEN ((CDS_IP_ID is null ) and (SAC_IP_ID is not null )) THEN ('1') ELSE ('0') END = '1') THEN (NULL) ELSE (CDS_IP_TCV_FULL_CUD_V_ID) END as IP_TCV_FULL_CUD_V_ID, SAC_IP_ID as IP_ID, SAC_IP_SUP_KEY as IP_SUP_KEY, SAC_MSTR_SRC_STM_CD as MSTR_SRC_STM_CD, SAC_ENT_TP_CD as ENT_TP_CD, SAC_MSTR_SRC_STM_KEY as MSTR_SRC_STM_KEY, SAC_SRC_STM_CD as SRC_STM_CD, SAC_HASH_VAL as HASH_VAL, {{ parse_datetime(var("pm_pcs_period")) }} as VLD_FROM_TMS, SAC_DEL_IN_SRC_STM_IND as DEL_IN_SRC_STM_IND, SAC_SRC_INSTN_ISRT_ID as SRC_INSTN_ISRT_ID, {{ var("pm_pcs_id") }} as PCS_ISRT_ID, CURRENT_DATETIME as ISRT_TMS, SAC_TC_OBJ_INSTANCE_KEY_1 as TC_OBJ_INSTANCE_KEY_1, SAC_TC_OBJ_INSTANCE_KEY_2 as TC_OBJ_INSTANCE_KEY_2, SAC_TC_OBJ_INSTANCE_KEY_3 as TC_OBJ_INSTANCE_KEY_3, SAC_TC_DATA_TYPE_CHAR_IND_CHANGED_NAME as TC_DATA_TYPE_CHAR_IND_CHANGED_NAME, SAC_TC_DATA_TYPE_NCHAR_CD as TC_DATA_TYPE_NCHAR_CD, SAC_TC_DATA_TYPE_VARCHAR_NM as TC_DATA_TYPE_VARCHAR_NM, SAC_TC_DATA_TYPE_NVARCHAR_DSC as TC_DATA_TYPE_NVARCHAR_DSC, SAC_TC_DATA_TYPE_INTEGER_RTO as TC_DATA_TYPE_INTEGER_RTO, SAC_TC_DATA_TYPE_SMALLINT_NBR as TC_DATA_TYPE_SMALLINT_NBR, SAC_TC_DATA_TYPE_BIGINT_PCT as TC_DATA_TYPE_BIGINT_PCT, SAC_TC_DATA_TYPE_DECIMAL_AMT as TC_DATA_TYPE_DECIMAL_AMT, SAC_TC_DATA_TYPE_BOOLEAN_F as TC_DATA_TYPE_BOOLEAN_F, SAC_TC_DATA_TYPE_TIMESTAMP_TMS as TC_DATA_TYPE_TIMESTAMP_TMS, SAC_TC_DATA_TYPE_DATE_DT as TC_DATA_TYPE_DATE_DT, SAC_TC_DATA_TYPE_TIME_TM as TC_DATA_TYPE_TIME_TM, SAC_TC_FK_CL_1_KEY_1 as TC_FK_CL_1_KEY_1, SAC_TC_FK_CL_1_KEY_2 as TC_FK_CL_1_KEY_2, SAC_TC_FK_CL_2_KEY as TC_FK_CL_2_KEY, SAC_TC_FK_EV_I_KEY as TC_FK_EV_I_KEY, SAC_TC_EDC_ATTR_SPLIT as TC_EDC_ATTR_SPLIT, SAC_TC_EDC_ATTR_CONVERGE_1 as TC_EDC_ATTR_CONVERGE_1, SAC_TC_EDC_ATTR_CONVERGE_2 as TC_EDC_ATTR_CONVERGE_2, SAC_TC_FK_1_CL_ID as TC_FK_1_CL_ID, SAC_TC_FK_2_CL_ID as TC_FK_2_CL_ID, SAC_TC_FK_EV_I_ID as TC_FK_EV_I_ID, SAC_TC_SPLIT_ATTR_1_EDC as TC_SPLIT_ATTR_1_EDC, SAC_TC_SPLIT_ATTR_2_EDC as TC_SPLIT_ATTR_2_EDC, SAC_TC_CONVERGE_ATTR_EDC as TC_CONVERGE_ATTR_EDC 
from  
(select BALOP_4.SAC_IP_ID as SAC_IP_ID, BALOP_4.SAC_IP_SUP_KEY as SAC_IP_SUP_KEY, BALOP_4.SAC_MSTR_SRC_STM_CD as SAC_MSTR_SRC_STM_CD, BALOP_4.SAC_ENT_TP_CD as SAC_ENT_TP_CD, BALOP_4.SAC_MSTR_SRC_STM_KEY as SAC_MSTR_SRC_STM_KEY, BALOP_4.SAC_SRC_STM_CD as SAC_SRC_STM_CD, BALOP_4.SAC_HASH_VAL as SAC_HASH_VAL, BALOP_4.SAC_VLD_FROM_TMS as SAC_VLD_FROM_TMS, BALOP_4.SAC_DEL_IN_SRC_STM_IND as SAC_DEL_IN_SRC_STM_IND, BALOP_4.SAC_SRC_INSTN_ISRT_ID as SAC_SRC_INSTN_ISRT_ID, BALOP_4.SAC_TC_OBJ_INSTANCE_KEY_1 as SAC_TC_OBJ_INSTANCE_KEY_1, BALOP_4.SAC_TC_OBJ_INSTANCE_KEY_2 as SAC_TC_OBJ_INSTANCE_KEY_2, BALOP_4.SAC_TC_OBJ_INSTANCE_KEY_3 as SAC_TC_OBJ_INSTANCE_KEY_3, BALOP_4.SAC_TC_DATA_TYPE_CHAR_IND_CHANGED_NAME as SAC_TC_DATA_TYPE_CHAR_IND_CHANGED_NAME, BALOP_4.SAC_TC_DATA_TYPE_NCHAR_CD as SAC_TC_DATA_TYPE_NCHAR_CD, BALOP_4.SAC_TC_DATA_TYPE_VARCHAR_NM as SAC_TC_DATA_TYPE_VARCHAR_NM, BALOP_4.SAC_TC_DATA_TYPE_NVARCHAR_DSC as SAC_TC_DATA_TYPE_NVARCHAR_DSC, BALOP_4.SAC_TC_DATA_TYPE_INTEGER_RTO as SAC_TC_DATA_TYPE_INTEGER_RTO, BALOP_4.SAC_TC_DATA_TYPE_SMALLINT_NBR as SAC_TC_DATA_TYPE_SMALLINT_NBR, BALOP_4.SAC_TC_DATA_TYPE_BIGINT_PCT as SAC_TC_DATA_TYPE_BIGINT_PCT, BALOP_4.SAC_TC_DATA_TYPE_DECIMAL_AMT as SAC_TC_DATA_TYPE_DECIMAL_AMT, BALOP_4.SAC_TC_DATA_TYPE_BOOLEAN_F as SAC_TC_DATA_TYPE_BOOLEAN_F, BALOP_4.SAC_TC_DATA_TYPE_TIMESTAMP_TMS as SAC_TC_DATA_TYPE_TIMESTAMP_TMS, BALOP_4.SAC_TC_DATA_TYPE_DATE_DT as SAC_TC_DATA_TYPE_DATE_DT, BALOP_4.SAC_TC_DATA_TYPE_TIME_TM as SAC_TC_DATA_TYPE_TIME_TM, BALOP_4.SAC_TC_FK_CL_1_KEY_1 as SAC_TC_FK_CL_1_KEY_1, BALOP_4.SAC_TC_FK_CL_1_KEY_2 as SAC_TC_FK_CL_1_KEY_2, BALOP_4.SAC_TC_FK_CL_2_KEY as SAC_TC_FK_CL_2_KEY, BALOP_4.SAC_TC_FK_EV_I_KEY as SAC_TC_FK_EV_I_KEY, BALOP_4.SAC_TC_EDC_ATTR_SPLIT as SAC_TC_EDC_ATTR_SPLIT, BALOP_4.SAC_TC_EDC_ATTR_CONVERGE_1 as SAC_TC_EDC_ATTR_CONVERGE_1, BALOP_4.SAC_TC_EDC_ATTR_CONVERGE_2 as SAC_TC_EDC_ATTR_CONVERGE_2, BALOP_4.SAC_TC_FK_1_CL_ID as SAC_TC_FK_1_CL_ID, BALOP_4.SAC_TC_FK_2_CL_ID as SAC_TC_FK_2_CL_ID, BALOP_4.SAC_TC_FK_EV_I_ID as SAC_TC_FK_EV_I_ID, BALOP_4.SAC_TC_SPLIT_ATTR_1_EDC as SAC_TC_SPLIT_ATTR_1_EDC, BALOP_4.SAC_TC_SPLIT_ATTR_2_EDC as SAC_TC_SPLIT_ATTR_2_EDC, BALOP_4.SAC_TC_CONVERGE_ATTR_EDC as SAC_TC_CONVERGE_ATTR_EDC, BALOP_7.CDS_IP_TCV_FULL_CUD_V_ID as CDS_IP_TCV_FULL_CUD_V_ID, BALOP_7.CDS_IP_ID as CDS_IP_ID, BALOP_7.CDS_IP_SUP_KEY as CDS_IP_SUP_KEY, BALOP_7.CDS_MSTR_SRC_STM_CD as CDS_MSTR_SRC_STM_CD, BALOP_7.CDS_ENT_TP_CD as CDS_ENT_TP_CD, BALOP_7.CDS_MSTR_SRC_STM_KEY as CDS_MSTR_SRC_STM_KEY, BALOP_7.CDS_SRC_STM_CD as CDS_SRC_STM_CD, BALOP_7.CDS_HASH_VAL as CDS_HASH_VAL, BALOP_7.CDS_VLD_FROM_TMS as CDS_VLD_FROM_TMS, BALOP_7.CDS_DEL_IN_SRC_STM_IND as CDS_DEL_IN_SRC_STM_IND, BALOP_7.CDS_SRC_INSTN_ISRT_ID as CDS_SRC_INSTN_ISRT_ID, BALOP_7.CDS_PCS_ISRT_ID as CDS_PCS_ISRT_ID, BALOP_7.CDS_ISRT_TMS as CDS_ISRT_TMS,  CASE WHEN (BALOP_7.CDS_TC_OBJ_INSTANCE_KEY_1 is null ) THEN ('') ELSE (BALOP_7.CDS_TC_OBJ_INSTANCE_KEY_1) END as CDS_TC_OBJ_INSTANCE_KEY_1,  CASE WHEN (BALOP_7.CDS_TC_OBJ_INSTANCE_KEY_2 is null ) THEN ('') ELSE (BALOP_7.CDS_TC_OBJ_INSTANCE_KEY_2) END as CDS_TC_OBJ_INSTANCE_KEY_2,  CASE WHEN (BALOP_7.CDS_TC_OBJ_INSTANCE_KEY_3 is null ) THEN ('') ELSE (BALOP_7.CDS_TC_OBJ_INSTANCE_KEY_3) END as CDS_TC_OBJ_INSTANCE_KEY_3, BALOP_7.CDS_TC_DATA_TYPE_CHAR_IND_CHANGED_NAME as CDS_TC_DATA_TYPE_CHAR_IND_CHANGED_NAME, BALOP_7.CDS_TC_DATA_TYPE_NCHAR_CD as CDS_TC_DATA_TYPE_NCHAR_CD, BALOP_7.CDS_TC_DATA_TYPE_VARCHAR_NM as CDS_TC_DATA_TYPE_VARCHAR_NM, BALOP_7.CDS_TC_DATA_TYPE_NVARCHAR_DSC as CDS_TC_DATA_TYPE_NVARCHAR_DSC, BALOP_7.CDS_TC_DATA_TYPE_INTEGER_RTO as CDS_TC_DATA_TYPE_INTEGER_RTO, BALOP_7.CDS_TC_DATA_TYPE_SMALLINT_NBR as CDS_TC_DATA_TYPE_SMALLINT_NBR, BALOP_7.CDS_TC_DATA_TYPE_BIGINT_PCT as CDS_TC_DATA_TYPE_BIGINT_PCT, BALOP_7.CDS_TC_DATA_TYPE_DECIMAL_AMT as CDS_TC_DATA_TYPE_DECIMAL_AMT, BALOP_7.CDS_TC_DATA_TYPE_BOOLEAN_F as CDS_TC_DATA_TYPE_BOOLEAN_F, BALOP_7.CDS_TC_DATA_TYPE_TIMESTAMP_TMS as CDS_TC_DATA_TYPE_TIMESTAMP_TMS, BALOP_7.CDS_TC_DATA_TYPE_DATE_DT as CDS_TC_DATA_TYPE_DATE_DT, BALOP_7.CDS_TC_DATA_TYPE_TIME_TM as CDS_TC_DATA_TYPE_TIME_TM,  CASE WHEN (BALOP_7.CDS_TC_FK_CL_1_KEY_1 is null ) THEN ('') ELSE (BALOP_7.CDS_TC_FK_CL_1_KEY_1) END as CDS_TC_FK_CL_1_KEY_1,  CASE WHEN (BALOP_7.CDS_TC_FK_CL_1_KEY_2 is null ) THEN ('') ELSE (BALOP_7.CDS_TC_FK_CL_1_KEY_2) END as CDS_TC_FK_CL_1_KEY_2,  CASE WHEN (BALOP_7.CDS_TC_FK_CL_2_KEY is null ) THEN ('') ELSE (BALOP_7.CDS_TC_FK_CL_2_KEY) END as CDS_TC_FK_CL_2_KEY, BALOP_7.CDS_TC_FK_EV_I_KEY as CDS_TC_FK_EV_I_KEY,  CASE WHEN (BALOP_7.CDS_TC_EDC_ATTR_SPLIT is null ) THEN ('') ELSE (BALOP_7.CDS_TC_EDC_ATTR_SPLIT) END as CDS_TC_EDC_ATTR_SPLIT, BALOP_7.CDS_TC_EDC_ATTR_CONVERGE_1 as CDS_TC_EDC_ATTR_CONVERGE_1, BALOP_7.CDS_TC_EDC_ATTR_CONVERGE_2 as CDS_TC_EDC_ATTR_CONVERGE_2,  CASE WHEN (BALOP_7.CDS_TC_FK_1_CL_ID is null ) THEN ('0') ELSE (BALOP_7.CDS_TC_FK_1_CL_ID) END as CDS_TC_FK_1_CL_ID, BALOP_7.CDS_TC_FK_2_CL_ID as CDS_TC_FK_2_CL_ID,  CASE WHEN (BALOP_7.CDS_TC_FK_EV_I_ID is null ) THEN ('0') ELSE (BALOP_7.CDS_TC_FK_EV_I_ID) END as CDS_TC_FK_EV_I_ID,  CASE WHEN (BALOP_7.CDS_TC_SPLIT_ATTR_1_EDC is null ) THEN ('') ELSE (BALOP_7.CDS_TC_SPLIT_ATTR_1_EDC) END as CDS_TC_SPLIT_ATTR_1_EDC,  CASE WHEN (BALOP_7.CDS_TC_SPLIT_ATTR_2_EDC is null ) THEN ('') ELSE (BALOP_7.CDS_TC_SPLIT_ATTR_2_EDC) END as CDS_TC_SPLIT_ATTR_2_EDC, BALOP_7.CDS_TC_CONVERGE_ATTR_EDC as CDS_TC_CONVERGE_ATTR_EDC 
from  
(select BALOP_3.IP_ID as IP_ID, BALOP_3.SAC_IP_ID as SAC_IP_ID, BALOP_3.IP_SUP_KEY as SAC_IP_SUP_KEY, BALOP_3.MSTR_SRC_STM_CD as SAC_MSTR_SRC_STM_CD, BALOP_3.ENT_TP_CD as SAC_ENT_TP_CD, BALOP_3.MSTR_SRC_STM_KEY as SAC_MSTR_SRC_STM_KEY, BALOP_3.SRC_STM_CD as SAC_SRC_STM_CD, BALOP_3.HASH_VAL as SAC_HASH_VAL, BALOP_3.VLD_FROM_TMS as SAC_VLD_FROM_TMS, BALOP_3.DEL_IN_SRC_STM_IND as SAC_DEL_IN_SRC_STM_IND, BALOP_3.SRC_INSTN_ISRT_ID as SAC_SRC_INSTN_ISRT_ID, BALOP_3.TC_OBJ_INSTANCE_KEY_1 as SAC_TC_OBJ_INSTANCE_KEY_1, BALOP_3.TC_OBJ_INSTANCE_KEY_2 as SAC_TC_OBJ_INSTANCE_KEY_2, BALOP_3.TC_OBJ_INSTANCE_KEY_3 as SAC_TC_OBJ_INSTANCE_KEY_3, BALOP_3.TC_DATA_TYPE_CHAR_IND_CHANGED_NAME as SAC_TC_DATA_TYPE_CHAR_IND_CHANGED_NAME, BALOP_3.TC_DATA_TYPE_NCHAR_CD as SAC_TC_DATA_TYPE_NCHAR_CD, BALOP_3.TC_DATA_TYPE_VARCHAR_NM as SAC_TC_DATA_TYPE_VARCHAR_NM, BALOP_3.TC_DATA_TYPE_NVARCHAR_DSC as SAC_TC_DATA_TYPE_NVARCHAR_DSC, BALOP_3.TC_DATA_TYPE_INTEGER_RTO as SAC_TC_DATA_TYPE_INTEGER_RTO, BALOP_3.TC_DATA_TYPE_SMALLINT_NBR as SAC_TC_DATA_TYPE_SMALLINT_NBR, BALOP_3.TC_DATA_TYPE_BIGINT_PCT as SAC_TC_DATA_TYPE_BIGINT_PCT, BALOP_3.TC_DATA_TYPE_DECIMAL_AMT as SAC_TC_DATA_TYPE_DECIMAL_AMT, BALOP_3.TC_DATA_TYPE_BOOLEAN_F as SAC_TC_DATA_TYPE_BOOLEAN_F, BALOP_3.TC_DATA_TYPE_TIMESTAMP_TMS as SAC_TC_DATA_TYPE_TIMESTAMP_TMS, BALOP_3.TC_DATA_TYPE_DATE_DT as SAC_TC_DATA_TYPE_DATE_DT, BALOP_3.TC_DATA_TYPE_TIME_TM as SAC_TC_DATA_TYPE_TIME_TM, BALOP_3.TC_FK_CL_1_KEY_1 as SAC_TC_FK_CL_1_KEY_1, BALOP_3.TC_FK_CL_1_KEY_2 as SAC_TC_FK_CL_1_KEY_2, BALOP_3.TC_FK_CL_2_KEY as SAC_TC_FK_CL_2_KEY, BALOP_3.TC_FK_EV_I_KEY as SAC_TC_FK_EV_I_KEY, BALOP_3.TC_EDC_ATTR_SPLIT as SAC_TC_EDC_ATTR_SPLIT, BALOP_3.TC_EDC_ATTR_CONVERGE_1 as SAC_TC_EDC_ATTR_CONVERGE_1, BALOP_3.TC_EDC_ATTR_CONVERGE_2 as SAC_TC_EDC_ATTR_CONVERGE_2, BALOP_3.TC_FK_1_CL_ID as SAC_TC_FK_1_CL_ID, BALOP_3.TC_FK_2_CL_ID as SAC_TC_FK_2_CL_ID, BALOP_3.TC_FK_EV_I_ID as SAC_TC_FK_EV_I_ID, BALOP_3.TC_SPLIT_ATTR_1_EDC as SAC_TC_SPLIT_ATTR_1_EDC, BALOP_3.TC_SPLIT_ATTR_2_EDC as SAC_TC_SPLIT_ATTR_2_EDC, BALOP_3.TC_CONVERGE_ATTR_EDC as SAC_TC_CONVERGE_ATTR_EDC 
from  
(
SELECT
   IP_ID
 , IP_ID AS SAC_IP_ID
 , IP_SUP_KEY
 , MSTR_SRC_STM_CD
 , ENT_TP_CD
 , MSTR_SRC_STM_KEY
 , SRC_STM_CD
 , VLD_FROM_TMS
 , DEL_IN_SRC_STM_IND
 , SRC_INSTN_ISRT_ID
 , TC_OBJ_INSTANCE_KEY_1
 , TC_OBJ_INSTANCE_KEY_2
 , TC_OBJ_INSTANCE_KEY_3
 , TC_DATA_TYPE_CHAR_IND_CHANGED_NAME
 , TC_DATA_TYPE_NCHAR_CD
 , TC_DATA_TYPE_VARCHAR_NM
 , TC_DATA_TYPE_NVARCHAR_DSC
 , TC_DATA_TYPE_INTEGER_RTO
 , TC_DATA_TYPE_SMALLINT_NBR
 , TC_DATA_TYPE_BIGINT_PCT
 , TC_DATA_TYPE_DECIMAL_AMT
 , TC_DATA_TYPE_BOOLEAN_F
 , TC_DATA_TYPE_TIMESTAMP_TMS
 , TC_DATA_TYPE_DATE_DT
 , TC_DATA_TYPE_TIME_TM
 , TC_FK_CL_1_KEY_1
 , TC_FK_CL_1_KEY_2
 , TC_FK_CL_2_KEY
 , TC_FK_EV_I_KEY
 , TC_EDC_ATTR_SPLIT
 , TC_EDC_ATTR_CONVERGE_1
 , TC_EDC_ATTR_CONVERGE_2
 , TC_FK_1_CL_ID
 , TC_FK_2_CL_ID
 , TC_FK_EV_I_ID
 , TC_SPLIT_ATTR_1_EDC
 , TC_SPLIT_ATTR_2_EDC
 , TC_CONVERGE_ATTR_EDC
 , HASH_VAL
   FROM(
   SELECT
     R1.IP_ID
   , S.IP_SUP_KEY
   , S.MSTR_SRC_STM_CD
   , S.ENT_TP_CD
   , S.MSTR_SRC_STM_KEY
   , S.SRC_STM_CD
   , S.VLD_FROM_TMS
   , S.DEL_IN_SRC_STM_IND
   , S.SRC_INSTN_ISRT_ID
   , S.TC_OBJ_INSTANCE_KEY_1
   , S.TC_OBJ_INSTANCE_KEY_2
   , S.TC_OBJ_INSTANCE_KEY_3
   , S.TC_DATA_TYPE_CHAR_IND_CHANGED_NAME
   , S.TC_DATA_TYPE_NCHAR_CD
   , S.TC_DATA_TYPE_VARCHAR_NM
   , S.TC_DATA_TYPE_NVARCHAR_DSC
   , S.TC_DATA_TYPE_INTEGER_RTO
   , S.TC_DATA_TYPE_SMALLINT_NBR
   , S.TC_DATA_TYPE_BIGINT_PCT
   , S.TC_DATA_TYPE_DECIMAL_AMT
   , S.TC_DATA_TYPE_BOOLEAN_F
   , S.TC_DATA_TYPE_TIMESTAMP_TMS
   , S.TC_DATA_TYPE_DATE_DT
   , S.TC_DATA_TYPE_TIME_TM AS TC_DATA_TYPE_TIME_TM
   , S.TC_FK_CL_1_KEY_1
   , S.TC_FK_CL_1_KEY_2
   , S.TC_FK_CL_2_KEY
   , S.TC_FK_EV_I_KEY
   , S.TC_EDC_ATTR_SPLIT
   , S.TC_EDC_ATTR_CONVERGE_1
   , S.TC_EDC_ATTR_CONVERGE_2
   , LK_TC_FK_1_CL_SUP_KEY.CL_ID AS TC_FK_1_CL_ID
   , LK_TC_FK_2_CL_SUP_KEY.CL_ID AS TC_FK_2_CL_ID
   , LK_TC_FK_EV_I_SUP_KEY.EV_TCI_DELTA_C_I_ID AS TC_FK_EV_I_ID
   , S.TC_SPLIT_ATTR_1_EDC
   , S.TC_SPLIT_ATTR_2_EDC
   , S.TC_CONVERGE_ATTR_EDC
   , TO_HEX(SHA256(
     IFNULL( S.IP_SUP_KEY, '  ' )
     ||';'|| IFNULL( S.TC_OBJ_INSTANCE_KEY_1, '  ' )
     ||';'|| IFNULL( S.TC_OBJ_INSTANCE_KEY_2, '  ' )
     ||';'|| IFNULL( S.TC_OBJ_INSTANCE_KEY_3, '  ' )
     ||';'|| IFNULL( S.TC_DATA_TYPE_CHAR_IND_CHANGED_NAME, '  ' )
     ||';'|| IFNULL( S.TC_DATA_TYPE_NCHAR_CD, '  ' )
     ||';'|| IFNULL( S.TC_DATA_TYPE_VARCHAR_NM, '  ' )
     ||';'|| IFNULL( S.TC_DATA_TYPE_NVARCHAR_DSC, '  ' )
     ||';'|| IFNULL( S.TC_DATA_TYPE_INTEGER_RTO,0 )
     ||';'|| IFNULL( S.TC_DATA_TYPE_SMALLINT_NBR ,0)
     ||';'|| IFNULL( S.TC_DATA_TYPE_BIGINT_PCT ,0)
     ||';'|| IFNULL( S.TC_DATA_TYPE_DECIMAL_AMT,0 )
     ||';'|| IFNULL( S.TC_DATA_TYPE_BOOLEAN_F,0 )
     ||';'|| IFNULL( S.TC_DATA_TYPE_TIMESTAMP_TMS,CURRENT_DATETIME )
     ||';'|| IFNULL( S.TC_DATA_TYPE_DATE_DT,CURRENT_DATE )
     ||';'|| IFNULL(S.TC_DATA_TYPE_TIME_TM , '  ' )
     ||';'|| IFNULL( S.TC_FK_CL_1_KEY_1, '  ' )
     ||';'|| IFNULL( S.TC_FK_CL_1_KEY_2, '  ' )
     ||';'|| IFNULL( S.TC_FK_CL_2_KEY, '  ' )
     ||';'|| IFNULL( S.TC_FK_EV_I_KEY, '  ' )
     ||';'|| IFNULL( S.TC_EDC_ATTR_SPLIT, '  ' )
     ||';'|| IFNULL( S.TC_EDC_ATTR_CONVERGE_1, '  ' )
     ||';'|| IFNULL( S.TC_EDC_ATTR_CONVERGE_2, '  ' )
     ||';'|| IFNULL( S.TC_SPLIT_ATTR_1_EDC, '  ' )
     ||';'|| IFNULL( S.TC_SPLIT_ATTR_2_EDC, '  ' )
     ||';'|| IFNULL( S.TC_CONVERGE_ATTR_EDC, '  ' )
     ||';'|| IFNULL( LK_TC_FK_1_CL_SUP_KEY.CL_ID, '  ' )
     ||';'|| IFNULL( LK_TC_FK_2_CL_SUP_KEY.CL_ID,'  ' )
     ||';'|| IFNULL( LK_TC_FK_EV_I_SUP_KEY.EV_TCI_DELTA_C_I_ID ,'  ')
     )) AS HASH_VAL
FROM {{ ref('PMS_IS_SAC_DPL_SS_DPL_IP_TCV_FULL_CUD_V') }} S
INNER JOIN {{ source('pms_cds','PMS_IS_CDS_IP_K') }} R1 ON (S.IP_SUP_KEY = R1.IP_SUP_KEY) AND R1.ENT_TP_CD='IP_TCV_FULL_CUD'
INNER JOIN {{ source('pms_cds','PMS_IS_CDS_CL_K') }} LK_TC_FK_1_CL_SUP_KEY ON (S.TC_FK_1_CL_SUP_KEY = LK_TC_FK_1_CL_SUP_KEY.CL_SUP_KEY) AND LK_TC_FK_1_CL_SUP_KEY.ENT_TP_CD='CL_CV'
LEFT OUTER JOIN {{ source('pms_cds','PMS_IS_CDS_CL_K') }} LK_TC_FK_2_CL_SUP_KEY ON (S.TC_FK_2_CL_SUP_KEY = LK_TC_FK_2_CL_SUP_KEY.CL_SUP_KEY) AND LK_TC_FK_2_CL_SUP_KEY.ENT_TP_CD='CL_CV'
INNER JOIN {{ source('pms_cds','PMS_IS_CDS_SS_DPL_EV_TCI_DELTA_C_I') }} LK_TC_FK_EV_I_SUP_KEY ON (S.TC_FK_EV_I_SUP_KEY = LK_TC_FK_EV_I_SUP_KEY.EV_TCI_DELTA_C_I_SUP_KEY) AND LK_TC_FK_EV_I_SUP_KEY.ENT_TP_CD='EV_TCI_DELTA_C_I'
) D) BALOP_3) BALOP_4 
left outer join  
(select BALOP_6.IP_TCV_FULL_CUD_V_ID as CDS_IP_TCV_FULL_CUD_V_ID, BALOP_6.IP_ID as IP_ID, BALOP_6.CDS_IP_ID as CDS_IP_ID, BALOP_6.IP_SUP_KEY as CDS_IP_SUP_KEY, BALOP_6.MSTR_SRC_STM_CD as CDS_MSTR_SRC_STM_CD, BALOP_6.ENT_TP_CD as CDS_ENT_TP_CD, BALOP_6.MSTR_SRC_STM_KEY as CDS_MSTR_SRC_STM_KEY, BALOP_6.SRC_STM_CD as CDS_SRC_STM_CD, BALOP_6.HASH_VAL as CDS_HASH_VAL, BALOP_6.VLD_FROM_TMS as CDS_VLD_FROM_TMS, BALOP_6.DEL_IN_SRC_STM_IND as CDS_DEL_IN_SRC_STM_IND, BALOP_6.SRC_INSTN_ISRT_ID as CDS_SRC_INSTN_ISRT_ID, BALOP_6.PCS_ISRT_ID as CDS_PCS_ISRT_ID, BALOP_6.ISRT_TMS as CDS_ISRT_TMS, BALOP_6.TC_OBJ_INSTANCE_KEY_1 as CDS_TC_OBJ_INSTANCE_KEY_1, BALOP_6.TC_OBJ_INSTANCE_KEY_2 as CDS_TC_OBJ_INSTANCE_KEY_2, BALOP_6.TC_OBJ_INSTANCE_KEY_3 as CDS_TC_OBJ_INSTANCE_KEY_3, BALOP_6.TC_DATA_TYPE_CHAR_IND_CHANGED_NAME as CDS_TC_DATA_TYPE_CHAR_IND_CHANGED_NAME, BALOP_6.TC_DATA_TYPE_NCHAR_CD as CDS_TC_DATA_TYPE_NCHAR_CD, BALOP_6.TC_DATA_TYPE_VARCHAR_NM as CDS_TC_DATA_TYPE_VARCHAR_NM, BALOP_6.TC_DATA_TYPE_NVARCHAR_DSC as CDS_TC_DATA_TYPE_NVARCHAR_DSC, BALOP_6.TC_DATA_TYPE_INTEGER_RTO as CDS_TC_DATA_TYPE_INTEGER_RTO, BALOP_6.TC_DATA_TYPE_SMALLINT_NBR as CDS_TC_DATA_TYPE_SMALLINT_NBR, BALOP_6.TC_DATA_TYPE_BIGINT_PCT as CDS_TC_DATA_TYPE_BIGINT_PCT, BALOP_6.TC_DATA_TYPE_DECIMAL_AMT as CDS_TC_DATA_TYPE_DECIMAL_AMT, BALOP_6.TC_DATA_TYPE_BOOLEAN_F as CDS_TC_DATA_TYPE_BOOLEAN_F, BALOP_6.TC_DATA_TYPE_TIMESTAMP_TMS as CDS_TC_DATA_TYPE_TIMESTAMP_TMS, BALOP_6.TC_DATA_TYPE_DATE_DT as CDS_TC_DATA_TYPE_DATE_DT, BALOP_6.TC_DATA_TYPE_TIME_TM as CDS_TC_DATA_TYPE_TIME_TM, BALOP_6.TC_FK_CL_1_KEY_1 as CDS_TC_FK_CL_1_KEY_1, BALOP_6.TC_FK_CL_1_KEY_2 as CDS_TC_FK_CL_1_KEY_2, BALOP_6.TC_FK_CL_2_KEY as CDS_TC_FK_CL_2_KEY, BALOP_6.TC_FK_EV_I_KEY as CDS_TC_FK_EV_I_KEY, BALOP_6.TC_EDC_ATTR_SPLIT as CDS_TC_EDC_ATTR_SPLIT, BALOP_6.TC_EDC_ATTR_CONVERGE_1 as CDS_TC_EDC_ATTR_CONVERGE_1, BALOP_6.TC_EDC_ATTR_CONVERGE_2 as CDS_TC_EDC_ATTR_CONVERGE_2, BALOP_6.TC_FK_1_CL_ID as CDS_TC_FK_1_CL_ID, BALOP_6.TC_FK_2_CL_ID as CDS_TC_FK_2_CL_ID, BALOP_6.TC_FK_EV_I_ID as CDS_TC_FK_EV_I_ID, BALOP_6.TC_SPLIT_ATTR_1_EDC as CDS_TC_SPLIT_ATTR_1_EDC, BALOP_6.TC_SPLIT_ATTR_2_EDC as CDS_TC_SPLIT_ATTR_2_EDC, BALOP_6.TC_CONVERGE_ATTR_EDC as CDS_TC_CONVERGE_ATTR_EDC 
from  
(select IP_TCV_FULL_CUD_V_ID as IP_TCV_FULL_CUD_V_ID, IP_ID as IP_ID, IP_ID as CDS_IP_ID, IP_SUP_KEY as IP_SUP_KEY, MSTR_SRC_STM_CD as MSTR_SRC_STM_CD, ENT_TP_CD as ENT_TP_CD, MSTR_SRC_STM_KEY as MSTR_SRC_STM_KEY, SRC_STM_CD as SRC_STM_CD, HASH_VAL as HASH_VAL, VLD_FROM_TMS as VLD_FROM_TMS, DEL_IN_SRC_STM_IND as DEL_IN_SRC_STM_IND, SRC_INSTN_ISRT_ID as SRC_INSTN_ISRT_ID, PCS_ISRT_ID as PCS_ISRT_ID, ISRT_TMS as ISRT_TMS, TC_OBJ_INSTANCE_KEY_1 as TC_OBJ_INSTANCE_KEY_1, TC_OBJ_INSTANCE_KEY_2 as TC_OBJ_INSTANCE_KEY_2, TC_OBJ_INSTANCE_KEY_3 as TC_OBJ_INSTANCE_KEY_3, TC_DATA_TYPE_CHAR_IND_CHANGED_NAME as TC_DATA_TYPE_CHAR_IND_CHANGED_NAME, TC_DATA_TYPE_NCHAR_CD as TC_DATA_TYPE_NCHAR_CD, TC_DATA_TYPE_VARCHAR_NM as TC_DATA_TYPE_VARCHAR_NM, TC_DATA_TYPE_NVARCHAR_DSC as TC_DATA_TYPE_NVARCHAR_DSC, TC_DATA_TYPE_INTEGER_RTO as TC_DATA_TYPE_INTEGER_RTO, TC_DATA_TYPE_SMALLINT_NBR as TC_DATA_TYPE_SMALLINT_NBR, TC_DATA_TYPE_BIGINT_PCT as TC_DATA_TYPE_BIGINT_PCT, TC_DATA_TYPE_DECIMAL_AMT as TC_DATA_TYPE_DECIMAL_AMT, TC_DATA_TYPE_BOOLEAN_F as TC_DATA_TYPE_BOOLEAN_F, TC_DATA_TYPE_TIMESTAMP_TMS as TC_DATA_TYPE_TIMESTAMP_TMS, TC_DATA_TYPE_DATE_DT as TC_DATA_TYPE_DATE_DT, (TC_DATA_TYPE_TIME_TM ) as TC_DATA_TYPE_TIME_TM, TC_FK_CL_1_KEY_1 as TC_FK_CL_1_KEY_1, TC_FK_CL_1_KEY_2 as TC_FK_CL_1_KEY_2, TC_FK_CL_2_KEY as TC_FK_CL_2_KEY, TC_FK_EV_I_KEY as TC_FK_EV_I_KEY, TC_EDC_ATTR_SPLIT as TC_EDC_ATTR_SPLIT, TC_EDC_ATTR_CONVERGE_1 as TC_EDC_ATTR_CONVERGE_1, TC_EDC_ATTR_CONVERGE_2 as TC_EDC_ATTR_CONVERGE_2, TC_FK_1_CL_ID as TC_FK_1_CL_ID, TC_FK_2_CL_ID as TC_FK_2_CL_ID, TC_FK_EV_I_ID as TC_FK_EV_I_ID, TC_SPLIT_ATTR_1_EDC as TC_SPLIT_ATTR_1_EDC, TC_SPLIT_ATTR_2_EDC as TC_SPLIT_ATTR_2_EDC, TC_CONVERGE_ATTR_EDC as TC_CONVERGE_ATTR_EDC 
from {{ source('pms_cds','PMS_IS_CDS_SS_DPL_IP_TCV_FULL_CUD_V') }}  BALOP_5 
where VLD_TO_TMS = CAST('9999-12-31 00:00:00' AS DATETIME)
) BALOP_6) BALOP_7 
on (BALOP_4.IP_ID = BALOP_7.IP_ID)) BALOP_8 
where (( CASE WHEN ((CDS_IP_ID is null ) and (SAC_IP_ID is not null )) THEN ('1') ELSE ('0') END = '1') or ( CASE WHEN ((CDS_IP_ID = SAC_IP_ID) and (SAC_HASH_VAL <> CDS_HASH_VAL)) THEN ('1') ELSE ('0') END = '1')) or ( CASE WHEN ((CDS_IP_ID = SAC_IP_ID) and (CDS_DEL_IN_SRC_STM_IND = 'Y')) THEN ('1') ELSE ('0') END = '1')) BALOP_9) 
union all 
(select BALOP_16.IP_TCV_FULL_CUD_V_ID as IP_TCV_FULL_CUD_V_ID, BALOP_16.IP_ID as IP_ID, BALOP_16.IP_SUP_KEY as IP_SUP_KEY, BALOP_16.MSTR_SRC_STM_CD as MSTR_SRC_STM_CD, BALOP_16.ENT_TP_CD as ENT_TP_CD, BALOP_16.MSTR_SRC_STM_KEY as MSTR_SRC_STM_KEY, BALOP_16.SRC_STM_CD as SRC_STM_CD, BALOP_16.HASH_VAL as HASH_VAL, BALOP_16.VLD_FROM_TMS as VLD_FROM_TMS, BALOP_16.DEL_IN_SRC_STM_IND as DEL_IN_SRC_STM_IND, BALOP_16.SRC_INSTN_ISRT_ID as SRC_INSTN_ISRT_ID, BALOP_16.PCS_ISRT_ID as PCS_ISRT_ID, BALOP_16.ISRT_TMS as ISRT_TMS, BALOP_16.TC_OBJ_INSTANCE_KEY_1 as TC_OBJ_INSTANCE_KEY_1, BALOP_16.TC_OBJ_INSTANCE_KEY_2 as TC_OBJ_INSTANCE_KEY_2, BALOP_16.TC_OBJ_INSTANCE_KEY_3 as TC_OBJ_INSTANCE_KEY_3, BALOP_16.TC_DATA_TYPE_CHAR_IND_CHANGED_NAME as TC_DATA_TYPE_CHAR_IND_CHANGED_NAME, BALOP_16.TC_DATA_TYPE_NCHAR_CD as TC_DATA_TYPE_NCHAR_CD, BALOP_16.TC_DATA_TYPE_VARCHAR_NM as TC_DATA_TYPE_VARCHAR_NM, BALOP_16.TC_DATA_TYPE_NVARCHAR_DSC as TC_DATA_TYPE_NVARCHAR_DSC, BALOP_16.TC_DATA_TYPE_INTEGER_RTO as TC_DATA_TYPE_INTEGER_RTO, BALOP_16.TC_DATA_TYPE_SMALLINT_NBR as TC_DATA_TYPE_SMALLINT_NBR, BALOP_16.TC_DATA_TYPE_BIGINT_PCT as TC_DATA_TYPE_BIGINT_PCT, BALOP_16.TC_DATA_TYPE_DECIMAL_AMT as TC_DATA_TYPE_DECIMAL_AMT, BALOP_16.TC_DATA_TYPE_BOOLEAN_F as TC_DATA_TYPE_BOOLEAN_F, BALOP_16.TC_DATA_TYPE_TIMESTAMP_TMS as TC_DATA_TYPE_TIMESTAMP_TMS, BALOP_16.TC_DATA_TYPE_DATE_DT as TC_DATA_TYPE_DATE_DT, BALOP_16.TC_DATA_TYPE_TIME_TM as TC_DATA_TYPE_TIME_TM, BALOP_16.TC_FK_CL_1_KEY_1 as TC_FK_CL_1_KEY_1, BALOP_16.TC_FK_CL_1_KEY_2 as TC_FK_CL_1_KEY_2, BALOP_16.TC_FK_CL_2_KEY as TC_FK_CL_2_KEY, BALOP_16.TC_FK_EV_I_KEY as TC_FK_EV_I_KEY, BALOP_16.TC_EDC_ATTR_SPLIT as TC_EDC_ATTR_SPLIT, BALOP_16.TC_EDC_ATTR_CONVERGE_1 as TC_EDC_ATTR_CONVERGE_1, BALOP_16.TC_EDC_ATTR_CONVERGE_2 as TC_EDC_ATTR_CONVERGE_2, BALOP_16.TC_FK_1_CL_ID as TC_FK_1_CL_ID, BALOP_16.TC_FK_2_CL_ID as TC_FK_2_CL_ID, BALOP_16.TC_FK_EV_I_ID as TC_FK_EV_I_ID, BALOP_16.TC_SPLIT_ATTR_1_EDC as TC_SPLIT_ATTR_1_EDC, BALOP_16.TC_SPLIT_ATTR_2_EDC as TC_SPLIT_ATTR_2_EDC, BALOP_16.TC_CONVERGE_ATTR_EDC as TC_CONVERGE_ATTR_EDC 
from  
(select CDS_IP_TCV_FULL_CUD_V_ID as IP_TCV_FULL_CUD_V_ID, CDS_IP_ID as IP_ID, CDS_IP_SUP_KEY as IP_SUP_KEY, CDS_MSTR_SRC_STM_CD as MSTR_SRC_STM_CD, CDS_ENT_TP_CD as ENT_TP_CD, CDS_MSTR_SRC_STM_KEY as MSTR_SRC_STM_KEY, CDS_SRC_STM_CD as SRC_STM_CD, CDS_HASH_VAL as HASH_VAL, {{ parse_datetime(var("pm_pcs_period")) }} as VLD_FROM_TMS, 'Y' as DEL_IN_SRC_STM_IND, CDS_SRC_INSTN_ISRT_ID as SRC_INSTN_ISRT_ID, 1 as PCS_ISRT_ID, CURRENT_DATETIME as ISRT_TMS, CDS_TC_OBJ_INSTANCE_KEY_1 as TC_OBJ_INSTANCE_KEY_1, CDS_TC_OBJ_INSTANCE_KEY_2 as TC_OBJ_INSTANCE_KEY_2, CDS_TC_OBJ_INSTANCE_KEY_3 as TC_OBJ_INSTANCE_KEY_3, CDS_TC_DATA_TYPE_CHAR_IND_CHANGED_NAME as TC_DATA_TYPE_CHAR_IND_CHANGED_NAME, CDS_TC_DATA_TYPE_NCHAR_CD as TC_DATA_TYPE_NCHAR_CD, CDS_TC_DATA_TYPE_VARCHAR_NM as TC_DATA_TYPE_VARCHAR_NM, CDS_TC_DATA_TYPE_NVARCHAR_DSC as TC_DATA_TYPE_NVARCHAR_DSC, CDS_TC_DATA_TYPE_INTEGER_RTO as TC_DATA_TYPE_INTEGER_RTO, CDS_TC_DATA_TYPE_SMALLINT_NBR as TC_DATA_TYPE_SMALLINT_NBR, CDS_TC_DATA_TYPE_BIGINT_PCT as TC_DATA_TYPE_BIGINT_PCT, CDS_TC_DATA_TYPE_DECIMAL_AMT as TC_DATA_TYPE_DECIMAL_AMT, CDS_TC_DATA_TYPE_BOOLEAN_F as TC_DATA_TYPE_BOOLEAN_F, CDS_TC_DATA_TYPE_TIMESTAMP_TMS as TC_DATA_TYPE_TIMESTAMP_TMS, CDS_TC_DATA_TYPE_DATE_DT as TC_DATA_TYPE_DATE_DT, SUBSTR(CDS_TC_DATA_TYPE_TIME_TM,INSTR(CDS_TC_DATA_TYPE_TIME_TM,'',1,2 - 1) + 1,(INSTR(CDS_TC_DATA_TYPE_TIME_TM,'',1,2) - INSTR(CDS_TC_DATA_TYPE_TIME_TM,'',1,2 - 1)) - 1) as TC_DATA_TYPE_TIME_TM, CDS_TC_FK_CL_1_KEY_1 as TC_FK_CL_1_KEY_1, CDS_TC_FK_CL_1_KEY_2 as TC_FK_CL_1_KEY_2, CDS_TC_FK_CL_2_KEY as TC_FK_CL_2_KEY, CDS_TC_FK_EV_I_KEY as TC_FK_EV_I_KEY, CDS_TC_EDC_ATTR_SPLIT as TC_EDC_ATTR_SPLIT, CDS_TC_EDC_ATTR_CONVERGE_1 as TC_EDC_ATTR_CONVERGE_1, CDS_TC_EDC_ATTR_CONVERGE_2 as TC_EDC_ATTR_CONVERGE_2, CDS_TC_FK_1_CL_ID as TC_FK_1_CL_ID, CDS_TC_FK_2_CL_ID as TC_FK_2_CL_ID, CDS_TC_FK_EV_I_ID as TC_FK_EV_I_ID, CDS_TC_SPLIT_ATTR_1_EDC as TC_SPLIT_ATTR_1_EDC, CDS_TC_SPLIT_ATTR_2_EDC as TC_SPLIT_ATTR_2_EDC, CDS_TC_CONVERGE_ATTR_EDC as TC_CONVERGE_ATTR_EDC 
from  
(select BALOP_11.SAC_IP_ID as SAC_IP_ID, BALOP_11.SAC_IP_SUP_KEY as SAC_IP_SUP_KEY, BALOP_11.SAC_MSTR_SRC_STM_CD as SAC_MSTR_SRC_STM_CD, BALOP_11.SAC_ENT_TP_CD as SAC_ENT_TP_CD, BALOP_11.SAC_MSTR_SRC_STM_KEY as SAC_MSTR_SRC_STM_KEY, BALOP_11.SAC_SRC_STM_CD as SAC_SRC_STM_CD, BALOP_11.SAC_HASH_VAL as SAC_HASH_VAL, BALOP_11.SAC_VLD_FROM_TMS as SAC_VLD_FROM_TMS, BALOP_11.SAC_DEL_IN_SRC_STM_IND as SAC_DEL_IN_SRC_STM_IND, BALOP_11.SAC_SRC_INSTN_ISRT_ID as SAC_SRC_INSTN_ISRT_ID,  CASE WHEN (BALOP_11.SAC_TC_OBJ_INSTANCE_KEY_1 is null ) THEN ('') ELSE (BALOP_11.SAC_TC_OBJ_INSTANCE_KEY_1) END as SAC_TC_OBJ_INSTANCE_KEY_1,  CASE WHEN (BALOP_11.SAC_TC_OBJ_INSTANCE_KEY_2 is null ) THEN ('') ELSE (BALOP_11.SAC_TC_OBJ_INSTANCE_KEY_2) END as SAC_TC_OBJ_INSTANCE_KEY_2,  CASE WHEN (BALOP_11.SAC_TC_OBJ_INSTANCE_KEY_3 is null ) THEN ('') ELSE (BALOP_11.SAC_TC_OBJ_INSTANCE_KEY_3) END as SAC_TC_OBJ_INSTANCE_KEY_3, BALOP_11.SAC_TC_DATA_TYPE_CHAR_IND_CHANGED_NAME as SAC_TC_DATA_TYPE_CHAR_IND_CHANGED_NAME, BALOP_11.SAC_TC_DATA_TYPE_NCHAR_CD as SAC_TC_DATA_TYPE_NCHAR_CD, BALOP_11.SAC_TC_DATA_TYPE_VARCHAR_NM as SAC_TC_DATA_TYPE_VARCHAR_NM, BALOP_11.SAC_TC_DATA_TYPE_NVARCHAR_DSC as SAC_TC_DATA_TYPE_NVARCHAR_DSC, BALOP_11.SAC_TC_DATA_TYPE_INTEGER_RTO as SAC_TC_DATA_TYPE_INTEGER_RTO, BALOP_11.SAC_TC_DATA_TYPE_SMALLINT_NBR as SAC_TC_DATA_TYPE_SMALLINT_NBR, BALOP_11.SAC_TC_DATA_TYPE_BIGINT_PCT as SAC_TC_DATA_TYPE_BIGINT_PCT, BALOP_11.SAC_TC_DATA_TYPE_DECIMAL_AMT as SAC_TC_DATA_TYPE_DECIMAL_AMT, BALOP_11.SAC_TC_DATA_TYPE_BOOLEAN_F as SAC_TC_DATA_TYPE_BOOLEAN_F, BALOP_11.SAC_TC_DATA_TYPE_TIMESTAMP_TMS as SAC_TC_DATA_TYPE_TIMESTAMP_TMS, BALOP_11.SAC_TC_DATA_TYPE_DATE_DT as SAC_TC_DATA_TYPE_DATE_DT, BALOP_11.SAC_TC_DATA_TYPE_TIME_TM as SAC_TC_DATA_TYPE_TIME_TM,  CASE WHEN (BALOP_11.SAC_TC_FK_CL_1_KEY_1 is null ) THEN ('') ELSE (BALOP_11.SAC_TC_FK_CL_1_KEY_1) END as SAC_TC_FK_CL_1_KEY_1,  CASE WHEN (BALOP_11.SAC_TC_FK_CL_1_KEY_2 is null ) THEN ('') ELSE (BALOP_11.SAC_TC_FK_CL_1_KEY_2) END as SAC_TC_FK_CL_1_KEY_2,  CASE WHEN (BALOP_11.SAC_TC_FK_CL_2_KEY is null ) THEN ('') ELSE (BALOP_11.SAC_TC_FK_CL_2_KEY) END as SAC_TC_FK_CL_2_KEY, BALOP_11.SAC_TC_FK_EV_I_KEY as SAC_TC_FK_EV_I_KEY,  CASE WHEN (BALOP_11.SAC_TC_EDC_ATTR_SPLIT is null ) THEN ('') ELSE (BALOP_11.SAC_TC_EDC_ATTR_SPLIT) END as SAC_TC_EDC_ATTR_SPLIT, BALOP_11.SAC_TC_EDC_ATTR_CONVERGE_1 as SAC_TC_EDC_ATTR_CONVERGE_1, BALOP_11.SAC_TC_EDC_ATTR_CONVERGE_2 as SAC_TC_EDC_ATTR_CONVERGE_2,  CASE WHEN (BALOP_11.SAC_TC_FK_1_CL_ID is null ) THEN ('0') ELSE (BALOP_11.SAC_TC_FK_1_CL_ID) END as SAC_TC_FK_1_CL_ID, BALOP_11.SAC_TC_FK_2_CL_ID as SAC_TC_FK_2_CL_ID,  CASE WHEN (BALOP_11.SAC_TC_FK_EV_I_ID is null ) THEN ('0') ELSE (BALOP_11.SAC_TC_FK_EV_I_ID) END as SAC_TC_FK_EV_I_ID,  CASE WHEN (BALOP_11.SAC_TC_SPLIT_ATTR_1_EDC is null ) THEN ('') ELSE (BALOP_11.SAC_TC_SPLIT_ATTR_1_EDC) END as SAC_TC_SPLIT_ATTR_1_EDC,  CASE WHEN (BALOP_11.SAC_TC_SPLIT_ATTR_2_EDC is null ) THEN ('') ELSE (BALOP_11.SAC_TC_SPLIT_ATTR_2_EDC) END as SAC_TC_SPLIT_ATTR_2_EDC, BALOP_11.SAC_TC_CONVERGE_ATTR_EDC as SAC_TC_CONVERGE_ATTR_EDC, BALOP_14.CDS_IP_TCV_FULL_CUD_V_ID as CDS_IP_TCV_FULL_CUD_V_ID, BALOP_14.CDS_IP_ID as CDS_IP_ID, BALOP_14.CDS_IP_SUP_KEY as CDS_IP_SUP_KEY, BALOP_14.CDS_MSTR_SRC_STM_CD as CDS_MSTR_SRC_STM_CD, BALOP_14.CDS_ENT_TP_CD as CDS_ENT_TP_CD, BALOP_14.CDS_MSTR_SRC_STM_KEY as CDS_MSTR_SRC_STM_KEY, BALOP_14.CDS_SRC_STM_CD as CDS_SRC_STM_CD, BALOP_14.CDS_HASH_VAL as CDS_HASH_VAL, BALOP_14.CDS_VLD_FROM_TMS as CDS_VLD_FROM_TMS, BALOP_14.CDS_DEL_IN_SRC_STM_IND as CDS_DEL_IN_SRC_STM_IND, BALOP_14.CDS_SRC_INSTN_ISRT_ID as CDS_SRC_INSTN_ISRT_ID, BALOP_14.CDS_PCS_ISRT_ID as CDS_PCS_ISRT_ID, BALOP_14.CDS_ISRT_TMS as CDS_ISRT_TMS, BALOP_14.CDS_TC_OBJ_INSTANCE_KEY_1 as CDS_TC_OBJ_INSTANCE_KEY_1, BALOP_14.CDS_TC_OBJ_INSTANCE_KEY_2 as CDS_TC_OBJ_INSTANCE_KEY_2, BALOP_14.CDS_TC_OBJ_INSTANCE_KEY_3 as CDS_TC_OBJ_INSTANCE_KEY_3, BALOP_14.CDS_TC_DATA_TYPE_CHAR_IND_CHANGED_NAME as CDS_TC_DATA_TYPE_CHAR_IND_CHANGED_NAME, BALOP_14.CDS_TC_DATA_TYPE_NCHAR_CD as CDS_TC_DATA_TYPE_NCHAR_CD, BALOP_14.CDS_TC_DATA_TYPE_VARCHAR_NM as CDS_TC_DATA_TYPE_VARCHAR_NM, BALOP_14.CDS_TC_DATA_TYPE_NVARCHAR_DSC as CDS_TC_DATA_TYPE_NVARCHAR_DSC, BALOP_14.CDS_TC_DATA_TYPE_INTEGER_RTO as CDS_TC_DATA_TYPE_INTEGER_RTO, BALOP_14.CDS_TC_DATA_TYPE_SMALLINT_NBR as CDS_TC_DATA_TYPE_SMALLINT_NBR, BALOP_14.CDS_TC_DATA_TYPE_BIGINT_PCT as CDS_TC_DATA_TYPE_BIGINT_PCT, BALOP_14.CDS_TC_DATA_TYPE_DECIMAL_AMT as CDS_TC_DATA_TYPE_DECIMAL_AMT, BALOP_14.CDS_TC_DATA_TYPE_BOOLEAN_F as CDS_TC_DATA_TYPE_BOOLEAN_F, BALOP_14.CDS_TC_DATA_TYPE_TIMESTAMP_TMS as CDS_TC_DATA_TYPE_TIMESTAMP_TMS, BALOP_14.CDS_TC_DATA_TYPE_DATE_DT as CDS_TC_DATA_TYPE_DATE_DT, BALOP_14.CDS_TC_DATA_TYPE_TIME_TM as CDS_TC_DATA_TYPE_TIME_TM, BALOP_14.CDS_TC_FK_CL_1_KEY_1 as CDS_TC_FK_CL_1_KEY_1, BALOP_14.CDS_TC_FK_CL_1_KEY_2 as CDS_TC_FK_CL_1_KEY_2, BALOP_14.CDS_TC_FK_CL_2_KEY as CDS_TC_FK_CL_2_KEY, BALOP_14.CDS_TC_FK_EV_I_KEY as CDS_TC_FK_EV_I_KEY, BALOP_14.CDS_TC_EDC_ATTR_SPLIT as CDS_TC_EDC_ATTR_SPLIT, BALOP_14.CDS_TC_EDC_ATTR_CONVERGE_1 as CDS_TC_EDC_ATTR_CONVERGE_1, BALOP_14.CDS_TC_EDC_ATTR_CONVERGE_2 as CDS_TC_EDC_ATTR_CONVERGE_2, BALOP_14.CDS_TC_FK_1_CL_ID as CDS_TC_FK_1_CL_ID, BALOP_14.CDS_TC_FK_2_CL_ID as CDS_TC_FK_2_CL_ID, BALOP_14.CDS_TC_FK_EV_I_ID as CDS_TC_FK_EV_I_ID, BALOP_14.CDS_TC_SPLIT_ATTR_1_EDC as CDS_TC_SPLIT_ATTR_1_EDC, BALOP_14.CDS_TC_SPLIT_ATTR_2_EDC as CDS_TC_SPLIT_ATTR_2_EDC, BALOP_14.CDS_TC_CONVERGE_ATTR_EDC as CDS_TC_CONVERGE_ATTR_EDC 
from  
(select BALOP_3.IP_ID as IP_ID, BALOP_3.SAC_IP_ID as SAC_IP_ID, BALOP_3.IP_SUP_KEY as SAC_IP_SUP_KEY, BALOP_3.MSTR_SRC_STM_CD as SAC_MSTR_SRC_STM_CD, BALOP_3.ENT_TP_CD as SAC_ENT_TP_CD, BALOP_3.MSTR_SRC_STM_KEY as SAC_MSTR_SRC_STM_KEY, BALOP_3.SRC_STM_CD as SAC_SRC_STM_CD, BALOP_3.HASH_VAL as SAC_HASH_VAL, BALOP_3.VLD_FROM_TMS as SAC_VLD_FROM_TMS, BALOP_3.DEL_IN_SRC_STM_IND as SAC_DEL_IN_SRC_STM_IND, BALOP_3.SRC_INSTN_ISRT_ID as SAC_SRC_INSTN_ISRT_ID, BALOP_3.TC_OBJ_INSTANCE_KEY_1 as SAC_TC_OBJ_INSTANCE_KEY_1, BALOP_3.TC_OBJ_INSTANCE_KEY_2 as SAC_TC_OBJ_INSTANCE_KEY_2, BALOP_3.TC_OBJ_INSTANCE_KEY_3 as SAC_TC_OBJ_INSTANCE_KEY_3, BALOP_3.TC_DATA_TYPE_CHAR_IND_CHANGED_NAME as SAC_TC_DATA_TYPE_CHAR_IND_CHANGED_NAME, BALOP_3.TC_DATA_TYPE_NCHAR_CD as SAC_TC_DATA_TYPE_NCHAR_CD, BALOP_3.TC_DATA_TYPE_VARCHAR_NM as SAC_TC_DATA_TYPE_VARCHAR_NM, BALOP_3.TC_DATA_TYPE_NVARCHAR_DSC as SAC_TC_DATA_TYPE_NVARCHAR_DSC, BALOP_3.TC_DATA_TYPE_INTEGER_RTO as SAC_TC_DATA_TYPE_INTEGER_RTO, BALOP_3.TC_DATA_TYPE_SMALLINT_NBR as SAC_TC_DATA_TYPE_SMALLINT_NBR, BALOP_3.TC_DATA_TYPE_BIGINT_PCT as SAC_TC_DATA_TYPE_BIGINT_PCT, BALOP_3.TC_DATA_TYPE_DECIMAL_AMT as SAC_TC_DATA_TYPE_DECIMAL_AMT, BALOP_3.TC_DATA_TYPE_BOOLEAN_F as SAC_TC_DATA_TYPE_BOOLEAN_F, BALOP_3.TC_DATA_TYPE_TIMESTAMP_TMS as SAC_TC_DATA_TYPE_TIMESTAMP_TMS, BALOP_3.TC_DATA_TYPE_DATE_DT as SAC_TC_DATA_TYPE_DATE_DT, BALOP_3.TC_DATA_TYPE_TIME_TM as SAC_TC_DATA_TYPE_TIME_TM, BALOP_3.TC_FK_CL_1_KEY_1 as SAC_TC_FK_CL_1_KEY_1, BALOP_3.TC_FK_CL_1_KEY_2 as SAC_TC_FK_CL_1_KEY_2, BALOP_3.TC_FK_CL_2_KEY as SAC_TC_FK_CL_2_KEY, BALOP_3.TC_FK_EV_I_KEY as SAC_TC_FK_EV_I_KEY, BALOP_3.TC_EDC_ATTR_SPLIT as SAC_TC_EDC_ATTR_SPLIT, BALOP_3.TC_EDC_ATTR_CONVERGE_1 as SAC_TC_EDC_ATTR_CONVERGE_1, BALOP_3.TC_EDC_ATTR_CONVERGE_2 as SAC_TC_EDC_ATTR_CONVERGE_2, BALOP_3.TC_FK_1_CL_ID as SAC_TC_FK_1_CL_ID, BALOP_3.TC_FK_2_CL_ID as SAC_TC_FK_2_CL_ID, BALOP_3.TC_FK_EV_I_ID as SAC_TC_FK_EV_I_ID, BALOP_3.TC_SPLIT_ATTR_1_EDC as SAC_TC_SPLIT_ATTR_1_EDC, BALOP_3.TC_SPLIT_ATTR_2_EDC as SAC_TC_SPLIT_ATTR_2_EDC, BALOP_3.TC_CONVERGE_ATTR_EDC as SAC_TC_CONVERGE_ATTR_EDC 
from  
(
SELECT
   IP_ID
 , IP_ID AS SAC_IP_ID
 , IP_SUP_KEY
 , MSTR_SRC_STM_CD
 , ENT_TP_CD
 , MSTR_SRC_STM_KEY
 , SRC_STM_CD
 , VLD_FROM_TMS
 , DEL_IN_SRC_STM_IND
 , SRC_INSTN_ISRT_ID
 , TC_OBJ_INSTANCE_KEY_1
 , TC_OBJ_INSTANCE_KEY_2
 , TC_OBJ_INSTANCE_KEY_3
 , TC_DATA_TYPE_CHAR_IND_CHANGED_NAME
 , TC_DATA_TYPE_NCHAR_CD
 , TC_DATA_TYPE_VARCHAR_NM
 , TC_DATA_TYPE_NVARCHAR_DSC
 , TC_DATA_TYPE_INTEGER_RTO
 , TC_DATA_TYPE_SMALLINT_NBR
 , TC_DATA_TYPE_BIGINT_PCT
 , TC_DATA_TYPE_DECIMAL_AMT
 , TC_DATA_TYPE_BOOLEAN_F
 , TC_DATA_TYPE_TIMESTAMP_TMS
 , TC_DATA_TYPE_DATE_DT
 , TC_DATA_TYPE_TIME_TM
 , TC_FK_CL_1_KEY_1
 , TC_FK_CL_1_KEY_2
 , TC_FK_CL_2_KEY
 , TC_FK_EV_I_KEY
 , TC_EDC_ATTR_SPLIT
 , TC_EDC_ATTR_CONVERGE_1
 , TC_EDC_ATTR_CONVERGE_2
 , TC_FK_1_CL_ID
 , TC_FK_2_CL_ID
 , TC_FK_EV_I_ID
 , TC_SPLIT_ATTR_1_EDC
 , TC_SPLIT_ATTR_2_EDC
 , TC_CONVERGE_ATTR_EDC
 , HASH_VAL
   FROM(
   SELECT
     R1.IP_ID
   , S.IP_SUP_KEY
   , S.MSTR_SRC_STM_CD
   , S.ENT_TP_CD
   , S.MSTR_SRC_STM_KEY
   , S.SRC_STM_CD
   , S.VLD_FROM_TMS
   , S.DEL_IN_SRC_STM_IND
   , S.SRC_INSTN_ISRT_ID
   , S.TC_OBJ_INSTANCE_KEY_1
   , S.TC_OBJ_INSTANCE_KEY_2
   , S.TC_OBJ_INSTANCE_KEY_3
   , S.TC_DATA_TYPE_CHAR_IND_CHANGED_NAME
   , S.TC_DATA_TYPE_NCHAR_CD
   , S.TC_DATA_TYPE_VARCHAR_NM
   , S.TC_DATA_TYPE_NVARCHAR_DSC
   , S.TC_DATA_TYPE_INTEGER_RTO
   , S.TC_DATA_TYPE_SMALLINT_NBR
   , S.TC_DATA_TYPE_BIGINT_PCT
   , S.TC_DATA_TYPE_DECIMAL_AMT
   , S.TC_DATA_TYPE_BOOLEAN_F
   , S.TC_DATA_TYPE_TIMESTAMP_TMS
   , S.TC_DATA_TYPE_DATE_DT
   ,S.TC_DATA_TYPE_TIME_TM
   , S.TC_FK_CL_1_KEY_1
   , S.TC_FK_CL_1_KEY_2
   , S.TC_FK_CL_2_KEY
   , S.TC_FK_EV_I_KEY
   , S.TC_EDC_ATTR_SPLIT
   , S.TC_EDC_ATTR_CONVERGE_1
   , S.TC_EDC_ATTR_CONVERGE_2
   , LK_TC_FK_1_CL_SUP_KEY.CL_ID AS TC_FK_1_CL_ID
   , LK_TC_FK_2_CL_SUP_KEY.CL_ID AS TC_FK_2_CL_ID
   , LK_TC_FK_EV_I_SUP_KEY.EV_TCI_DELTA_C_I_ID AS TC_FK_EV_I_ID
   , S.TC_SPLIT_ATTR_1_EDC
   , S.TC_SPLIT_ATTR_2_EDC
   , S.TC_CONVERGE_ATTR_EDC
   , TO_HEX(SHA256(
     IFNULL( S.IP_SUP_KEY, '  ' )
     ||';'|| IFNULL( S.TC_OBJ_INSTANCE_KEY_1, '  ' )
     ||';'|| IFNULL( S.TC_OBJ_INSTANCE_KEY_2, '  ' )
     ||';'|| IFNULL( S.TC_OBJ_INSTANCE_KEY_3, '  ' )
     ||';'|| IFNULL( S.TC_DATA_TYPE_CHAR_IND_CHANGED_NAME, '  ' )
     ||';'|| IFNULL( S.TC_DATA_TYPE_NCHAR_CD, '  ' )
     ||';'|| IFNULL( S.TC_DATA_TYPE_VARCHAR_NM, '  ' )
     ||';'|| IFNULL( S.TC_DATA_TYPE_NVARCHAR_DSC, '  ' )
     ||';'|| IFNULL( S.TC_DATA_TYPE_INTEGER_RTO ,0)
     ||';'|| IFNULL( S.TC_DATA_TYPE_SMALLINT_NBR  ,0)
     ||';'|| IFNULL( S.TC_DATA_TYPE_BIGINT_PCT ,0 )
     ||';'|| IFNULL( S.TC_DATA_TYPE_DECIMAL_AMT ,0 )
     ||';'|| IFNULL( S.TC_DATA_TYPE_BOOLEAN_F ,0 )
     ||';'|| IFNULL( S.TC_DATA_TYPE_TIMESTAMP_TMS,CURRENT_DATETIME )
     ||';'|| IFNULL( S.TC_DATA_TYPE_DATE_DT,CURRENT_DATE )
     ||';'|| IFNULL(S.TC_DATA_TYPE_TIME_TM ,'  ' )
     ||';'|| IFNULL( S.TC_FK_CL_1_KEY_1, '  ' )
     ||';'|| IFNULL( S.TC_FK_CL_1_KEY_2, '  ' )
     ||';'|| IFNULL( S.TC_FK_CL_2_KEY, '  ' )
     ||';'|| IFNULL( S.TC_FK_EV_I_KEY, '  ' )
     ||';'|| IFNULL( S.TC_EDC_ATTR_SPLIT, '  ' )
     ||';'|| IFNULL( S.TC_EDC_ATTR_CONVERGE_1, '  ' )
     ||';'|| IFNULL( S.TC_EDC_ATTR_CONVERGE_2, '  ' )
     ||';'|| IFNULL( S.TC_SPLIT_ATTR_1_EDC, '  ' )
     ||';'|| IFNULL( S.TC_SPLIT_ATTR_2_EDC, '  ' )
     ||';'|| IFNULL( S.TC_CONVERGE_ATTR_EDC, '  ' )
     ||';'|| IFNULL( LK_TC_FK_1_CL_SUP_KEY.CL_ID , '  ')
     ||';'|| IFNULL( LK_TC_FK_2_CL_SUP_KEY.CL_ID ,'  ' )
     ||';'|| IFNULL( LK_TC_FK_EV_I_SUP_KEY.EV_TCI_DELTA_C_I_ID  ,'  ')
     )) AS HASH_VAL
FROM {{ ref('PMS_IS_SAC_DPL_SS_DPL_IP_TCV_FULL_CUD_V') }} S
INNER JOIN {{ source('pms_cds','PMS_IS_CDS_IP_K') }} R1 ON (S.IP_SUP_KEY = R1.IP_SUP_KEY) AND R1.ENT_TP_CD='IP_TCV_FULL_CUD'
INNER JOIN {{ source('pms_cds','PMS_IS_CDS_CL_K') }} LK_TC_FK_1_CL_SUP_KEY ON (S.TC_FK_1_CL_SUP_KEY = LK_TC_FK_1_CL_SUP_KEY.CL_SUP_KEY) AND LK_TC_FK_1_CL_SUP_KEY.ENT_TP_CD='CL_CV'
LEFT OUTER JOIN {{ source('pms_cds','PMS_IS_CDS_CL_K') }} LK_TC_FK_2_CL_SUP_KEY ON (S.TC_FK_2_CL_SUP_KEY = LK_TC_FK_2_CL_SUP_KEY.CL_SUP_KEY) AND LK_TC_FK_2_CL_SUP_KEY.ENT_TP_CD='CL_CV'
INNER JOIN {{ source('pms_cds','PMS_IS_CDS_SS_DPL_EV_TCI_DELTA_C_I') }} LK_TC_FK_EV_I_SUP_KEY ON (S.TC_FK_EV_I_SUP_KEY = LK_TC_FK_EV_I_SUP_KEY.EV_TCI_DELTA_C_I_SUP_KEY) AND LK_TC_FK_EV_I_SUP_KEY.ENT_TP_CD='EV_TCI_DELTA_C_I'
) D) BALOP_3) BALOP_11 
right outer join  
(select BALOP_6.IP_TCV_FULL_CUD_V_ID as CDS_IP_TCV_FULL_CUD_V_ID, BALOP_6.IP_ID as IP_ID, BALOP_6.CDS_IP_ID as CDS_IP_ID, BALOP_6.IP_SUP_KEY as CDS_IP_SUP_KEY, BALOP_6.MSTR_SRC_STM_CD as CDS_MSTR_SRC_STM_CD, BALOP_6.ENT_TP_CD as CDS_ENT_TP_CD, BALOP_6.MSTR_SRC_STM_KEY as CDS_MSTR_SRC_STM_KEY, BALOP_6.SRC_STM_CD as CDS_SRC_STM_CD, BALOP_6.HASH_VAL as CDS_HASH_VAL, BALOP_6.VLD_FROM_TMS as CDS_VLD_FROM_TMS, BALOP_6.DEL_IN_SRC_STM_IND as CDS_DEL_IN_SRC_STM_IND, BALOP_6.SRC_INSTN_ISRT_ID as CDS_SRC_INSTN_ISRT_ID, BALOP_6.PCS_ISRT_ID as CDS_PCS_ISRT_ID, BALOP_6.ISRT_TMS as CDS_ISRT_TMS, BALOP_6.TC_OBJ_INSTANCE_KEY_1 as CDS_TC_OBJ_INSTANCE_KEY_1, BALOP_6.TC_OBJ_INSTANCE_KEY_2 as CDS_TC_OBJ_INSTANCE_KEY_2, BALOP_6.TC_OBJ_INSTANCE_KEY_3 as CDS_TC_OBJ_INSTANCE_KEY_3, BALOP_6.TC_DATA_TYPE_CHAR_IND_CHANGED_NAME as CDS_TC_DATA_TYPE_CHAR_IND_CHANGED_NAME, BALOP_6.TC_DATA_TYPE_NCHAR_CD as CDS_TC_DATA_TYPE_NCHAR_CD, BALOP_6.TC_DATA_TYPE_VARCHAR_NM as CDS_TC_DATA_TYPE_VARCHAR_NM, BALOP_6.TC_DATA_TYPE_NVARCHAR_DSC as CDS_TC_DATA_TYPE_NVARCHAR_DSC, BALOP_6.TC_DATA_TYPE_INTEGER_RTO as CDS_TC_DATA_TYPE_INTEGER_RTO, BALOP_6.TC_DATA_TYPE_SMALLINT_NBR as CDS_TC_DATA_TYPE_SMALLINT_NBR, BALOP_6.TC_DATA_TYPE_BIGINT_PCT as CDS_TC_DATA_TYPE_BIGINT_PCT, BALOP_6.TC_DATA_TYPE_DECIMAL_AMT as CDS_TC_DATA_TYPE_DECIMAL_AMT, BALOP_6.TC_DATA_TYPE_BOOLEAN_F as CDS_TC_DATA_TYPE_BOOLEAN_F, BALOP_6.TC_DATA_TYPE_TIMESTAMP_TMS as CDS_TC_DATA_TYPE_TIMESTAMP_TMS, BALOP_6.TC_DATA_TYPE_DATE_DT as CDS_TC_DATA_TYPE_DATE_DT, BALOP_6.TC_DATA_TYPE_TIME_TM as CDS_TC_DATA_TYPE_TIME_TM, BALOP_6.TC_FK_CL_1_KEY_1 as CDS_TC_FK_CL_1_KEY_1, BALOP_6.TC_FK_CL_1_KEY_2 as CDS_TC_FK_CL_1_KEY_2, BALOP_6.TC_FK_CL_2_KEY as CDS_TC_FK_CL_2_KEY, BALOP_6.TC_FK_EV_I_KEY as CDS_TC_FK_EV_I_KEY, BALOP_6.TC_EDC_ATTR_SPLIT as CDS_TC_EDC_ATTR_SPLIT, BALOP_6.TC_EDC_ATTR_CONVERGE_1 as CDS_TC_EDC_ATTR_CONVERGE_1, BALOP_6.TC_EDC_ATTR_CONVERGE_2 as CDS_TC_EDC_ATTR_CONVERGE_2, BALOP_6.TC_FK_1_CL_ID as CDS_TC_FK_1_CL_ID, BALOP_6.TC_FK_2_CL_ID as CDS_TC_FK_2_CL_ID, BALOP_6.TC_FK_EV_I_ID as CDS_TC_FK_EV_I_ID, BALOP_6.TC_SPLIT_ATTR_1_EDC as CDS_TC_SPLIT_ATTR_1_EDC, BALOP_6.TC_SPLIT_ATTR_2_EDC as CDS_TC_SPLIT_ATTR_2_EDC, BALOP_6.TC_CONVERGE_ATTR_EDC as CDS_TC_CONVERGE_ATTR_EDC 
from  
(select IP_TCV_FULL_CUD_V_ID as IP_TCV_FULL_CUD_V_ID, IP_ID as IP_ID, IP_ID as CDS_IP_ID, IP_SUP_KEY as IP_SUP_KEY, MSTR_SRC_STM_CD as MSTR_SRC_STM_CD, ENT_TP_CD as ENT_TP_CD, MSTR_SRC_STM_KEY as MSTR_SRC_STM_KEY, SRC_STM_CD as SRC_STM_CD, HASH_VAL as HASH_VAL, VLD_FROM_TMS as VLD_FROM_TMS, DEL_IN_SRC_STM_IND as DEL_IN_SRC_STM_IND, SRC_INSTN_ISRT_ID as SRC_INSTN_ISRT_ID, PCS_ISRT_ID as PCS_ISRT_ID, ISRT_TMS as ISRT_TMS, TC_OBJ_INSTANCE_KEY_1 as TC_OBJ_INSTANCE_KEY_1, TC_OBJ_INSTANCE_KEY_2 as TC_OBJ_INSTANCE_KEY_2, TC_OBJ_INSTANCE_KEY_3 as TC_OBJ_INSTANCE_KEY_3, TC_DATA_TYPE_CHAR_IND_CHANGED_NAME as TC_DATA_TYPE_CHAR_IND_CHANGED_NAME, TC_DATA_TYPE_NCHAR_CD as TC_DATA_TYPE_NCHAR_CD, TC_DATA_TYPE_VARCHAR_NM as TC_DATA_TYPE_VARCHAR_NM, TC_DATA_TYPE_NVARCHAR_DSC as TC_DATA_TYPE_NVARCHAR_DSC, TC_DATA_TYPE_INTEGER_RTO as TC_DATA_TYPE_INTEGER_RTO, TC_DATA_TYPE_SMALLINT_NBR as TC_DATA_TYPE_SMALLINT_NBR, TC_DATA_TYPE_BIGINT_PCT as TC_DATA_TYPE_BIGINT_PCT, TC_DATA_TYPE_DECIMAL_AMT as TC_DATA_TYPE_DECIMAL_AMT, TC_DATA_TYPE_BOOLEAN_F as TC_DATA_TYPE_BOOLEAN_F, TC_DATA_TYPE_TIMESTAMP_TMS as TC_DATA_TYPE_TIMESTAMP_TMS, TC_DATA_TYPE_DATE_DT as TC_DATA_TYPE_DATE_DT, (TC_DATA_TYPE_TIME_TM ) as TC_DATA_TYPE_TIME_TM, TC_FK_CL_1_KEY_1 as TC_FK_CL_1_KEY_1, TC_FK_CL_1_KEY_2 as TC_FK_CL_1_KEY_2, TC_FK_CL_2_KEY as TC_FK_CL_2_KEY, TC_FK_EV_I_KEY as TC_FK_EV_I_KEY, TC_EDC_ATTR_SPLIT as TC_EDC_ATTR_SPLIT, TC_EDC_ATTR_CONVERGE_1 as TC_EDC_ATTR_CONVERGE_1, TC_EDC_ATTR_CONVERGE_2 as TC_EDC_ATTR_CONVERGE_2, TC_FK_1_CL_ID as TC_FK_1_CL_ID, TC_FK_2_CL_ID as TC_FK_2_CL_ID, TC_FK_EV_I_ID as TC_FK_EV_I_ID, TC_SPLIT_ATTR_1_EDC as TC_SPLIT_ATTR_1_EDC, TC_SPLIT_ATTR_2_EDC as TC_SPLIT_ATTR_2_EDC, TC_CONVERGE_ATTR_EDC as TC_CONVERGE_ATTR_EDC 
from {{ source('pms_cds','PMS_IS_CDS_SS_DPL_IP_TCV_FULL_CUD_V') }} BALOP_5 
where VLD_TO_TMS = CAST('9999-12-31 00:00:00' AS DATETIME)
) BALOP_6) BALOP_14 
on (BALOP_11.IP_ID = BALOP_14.IP_ID)) BALOP_15 
where  CASE WHEN (((SAC_IP_ID is null ) and (CDS_IP_ID is not null )) and (CDS_DEL_IN_SRC_STM_IND = 'N')) THEN ('1') ELSE ('0') END = '1') BALOP_16)

)