{{ config(
	    materialized="view",
	    schema='DIM'
	           ) }}
SELECT
 DISTINCT 
 ACCOUNT_ID||CUSTOMER_ID||ACCOUNT_TYPE||BRANCH_ID AS SUP_KEY,
 ACCOUNT_ID AS ACC_ID,
 CUSTOMER_ID AS CUSTOMERID,
 BALANCE,
 ACCOUNT_TYPE,
 BRANCH_ID,
 BRANCH_NAME,

 SHA1_HEX(ACCOUNT_ID||CUSTOMER_ID||BALANCE||ACCOUNT_TYPE||BRANCH_ID||BRANCH_NAME) AS HASH_VAL 
 FROM
 {{ref('RAW_ACCOUNTS')}}
