{{ config(
	    materialized="view",
	    schema='DIM'
	           ) }}
SELECT
 DISTINCT 
 CUSTOMER_ID AS CUST_ID,
 NAME AS CUSTOMER_NAME,
 JOIN_DATE,
 GENDER,
 MARITAL_STATUS,
 OCCUPATION,
 SHA1_HEX(CUST_ID||CUSTOMER_NAME||JOIN_DATE||GENDER||MARITAL_STATUS||OCCUPATION) AS HASH_VAL 
 FROM
 {{ref('RAW_CUSTOMER')}}
